export { default as Header } from './Header'
export { default as Navigation } from './Navigation'
export { default as Footer } from './Footer'
export { default as InputField } from './inputField'
export { default as Qrcode } from './Qrcode'
export { default as Test1} from './tesst'
export { default as Button1} from './button'
export { default as Button2} from './buttonOtp'
